### ISSUE TITLE
Missing dist folder in 0.0.3 version

### ISSUE THREAD

**Issue by MrRoiz** [dinkopehar/insomnia-plugin-theme-ayu#1]
Hey there, I just tried this theme, but I had to manually download and compile the project to be able to use it.

It looks great though!

**Comment by dinkopehar** [comment]
Hi @MrRoiz 

Thank you for noticing this problem :rocket: . When I changed my username, I only bumped a version without compiling with TypeScript. For that reason, `dist` folder was missing in whole package :roll_eyes: 

I faced same problem as you now, once I published a new version, it started working again :+1:

Please check if this solution works for you also. If it is, I will close the issue as done.

**Comment by MrRoiz** [comment]
Yes @dinkopehar, now I'm able to install the plugin as usual.
